on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: bun install

      - name: Build
        run: bun build

      - name: Deploy
        uses: actions/deploy-pages@v2
        with:
          branch: master
          github-token: ${{ secrets.GITHUB_TOKEN }}
